// <auto-generated />
using System;
using ADEO.MeetingApp.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADEO.MeetingApp.DAL.Migrations
{
    [DbContext(typeof(MeetingAppDBContext))]
    [Migration("20240811124634_initialDatabaseCreation")]
    partial class initialDatabaseCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ADEO.MeetingApp.DAL.Models.Attendees", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("DidAttend")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCalled")
                        .HasColumnType("bit");

                    b.Property<int>("MeetingID")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MeetingID");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("ADEO.MeetingApp.DAL.Models.CallHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AttendeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CallEndedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CalledOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("MeetingID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AttendeeID");

                    b.ToTable("CallHistory");
                });

            modelBuilder.Entity("ADEO.MeetingApp.DAL.Models.MeetingDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ComapnyLogoFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("FromTime")
                        .HasColumnType("time");

                    b.Property<string>("HostContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HostFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("ToTime")
                        .HasColumnType("time");

                    b.HasKey("ID");

                    b.ToTable("MeetingDetails");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ComapnyLogoFileName = "DU.png",
                            CompanyName = "DU",
                            Date = new DateOnly(2024, 8, 11),
                            FromTime = new TimeOnly(9, 0, 0),
                            HostContact = "5051",
                            HostFullName = "Mohamed Shaikh",
                            Name = "DU Product Launch",
                            RoomName = "#1 IT Room",
                            ToTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            ID = 2,
                            ComapnyLogoFileName = "Etisalat.png",
                            CompanyName = "Etisalat",
                            Date = new DateOnly(2024, 8, 11),
                            FromTime = new TimeOnly(11, 0, 0),
                            HostContact = "5150",
                            HostFullName = "Yasir Shaikh",
                            Name = "Etisalat Product Launch",
                            RoomName = "#5 Projector Room ",
                            ToTime = new TimeOnly(12, 0, 0)
                        },
                        new
                        {
                            ID = 3,
                            ComapnyLogoFileName = "ABC.png",
                            CompanyName = "ABC",
                            Date = new DateOnly(2024, 8, 11),
                            FromTime = new TimeOnly(14, 0, 0),
                            HostContact = "5012",
                            HostFullName = "Govinda Siddartha",
                            Name = "ABC Annual Review",
                            RoomName = "#7 Conference",
                            ToTime = new TimeOnly(16, 0, 0)
                        });
                });

            modelBuilder.Entity("ADEO.MeetingApp.DAL.Models.Attendees", b =>
                {
                    b.HasOne("ADEO.MeetingApp.DAL.Models.MeetingDetails", "MeetingDetails")
                        .WithMany()
                        .HasForeignKey("MeetingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetingDetails");
                });

            modelBuilder.Entity("ADEO.MeetingApp.DAL.Models.CallHistory", b =>
                {
                    b.HasOne("ADEO.MeetingApp.DAL.Models.Attendees", "Attendees")
                        .WithMany()
                        .HasForeignKey("AttendeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendees");
                });
#pragma warning restore 612, 618
        }
    }
}
